meta_product_name: "Wattivet"
meta_title: "Wattivet - La clinique vétérinaire de Wattignies"
meta_description: "Chat ou chien, notre équipe vétérinaire prend soin de votre compagnon à quatre pattes."
meta_image: "wattivet_cover.png" # should exist in `app/assets/images/`
